/*
 * Generate src/worldData.js from the images in public/world.
 *
 *   node scripts/gen-world.mjs      (or: npm run world)
 *
 * src, pixel dimensions (w/h) and alt are set automatically by scanning the
 * folder - just drop <N>.webp files into /public/world and re-run. The only
 * field that holds real metadata is `taken`: it is auto-derived when the
 * filename encodes a date (e.g. IMG20250716192813.webp), and otherwise carried
 * over from the existing manifest, so any date set by hand survives regeneration.
 */
import { readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import sharp from 'sharp';

const WORLD_DIR = path.resolve('public/world');
const OUT = path.resolve('src/worldData.js');
const WORLD_V = 2; // cache-bust query for the non-fingerprinted /world/* assets

// 1. Carry forward any `taken` dates already in the manifest (keyed by filename).
const existingTaken = {};
try {
  const mod = await import(pathToFileURL(OUT).href + '?t=' + Date.now());
  for (const p of mod.worldPhotos || []) {
    const m = String(p.src).match(/\/world\/([^?]+)/);
    if (m && p.taken) existingTaken[m[1]] = p.taken;
  }
} catch { /* no/unparseable manifest yet - start fresh */ }

// 2. Pull a date out of a filename when it encodes one (phone-style names).
function takenFromName(name) {
  const d = name.replace(/\.[^.]+$/, '').replace(/\D/g, ''); // digits only
  if (!/^\d{8}/.test(d)) return null;                        // need at least YYYYMMDD
  const Y = +d.slice(0, 4), Mo = +d.slice(4, 6), Da = +d.slice(6, 8);
  if (Y < 1990 || Y > 2100 || Mo < 1 || Mo > 12 || Da < 1 || Da > 31) return null;
  const date = `${d.slice(0, 4)}-${d.slice(4, 6)}-${d.slice(6, 8)}`;
  const H = d.slice(8, 10), Mi = d.slice(10, 12);
  return H && Mi ? `${date}T${H}:${Mi}` : date;
}

// 3. Scan the folder: numeric files (1.webp, 2.webp, ...) first, in order.
const files = (await readdir(WORLD_DIR))
  .filter((f) => /\.webp$/i.test(f))
  .sort((a, b) => {
    const aNum = /^\d/.test(a), bNum = /^\d/.test(b);
    if (aNum && bNum) return parseInt(a) - parseInt(b);
    if (aNum !== bNum) return aNum ? -1 : 1;
    return a.localeCompare(b);
  });

const rows = [];
for (let i = 0; i < files.length; i++) {
  const f = files[i];
  const { width, height } = await sharp(path.join(WORLD_DIR, f)).metadata();
  rows.push({
    src: `/world/${f}?v=${WORLD_V}`,
    w: width,
    h: height,
    alt: `Photograph ${String(i + 1).padStart(2, '0')}`,
    taken: takenFromName(f) ?? existingTaken[f] ?? null,
  });
}

// 4. Emit src/worldData.js (column-aligned, like the hand-written original).
const wPad = Math.max(...rows.map((r) => String(r.w).length)) + 1;
const hPad = Math.max(...rows.map((r) => String(r.h).length)) + 1;
const body = rows.map((r) => {
  const w = `${r.w},`.padEnd(wPad);
  const h = `${r.h},`.padEnd(hPad);
  const taken = r.taken ? `'${r.taken}'` : 'null';
  return `  { src: '${r.src}', w: ${w} h: ${h} alt: '${r.alt}', taken: ${taken} },`;
}).join('\n');

const out = `/* ============================================================
   World - the photo manifest.   GENERATED by scripts/gen-world.mjs.

   Drop <N>.webp files into /public/world and run:  npm run world
   src, dimensions (w/h) and alt are filled in automatically from the files.
   The ONLY field you set is \`taken\` (ISO 'YYYY-MM-DDTHH:mm'): it is auto-derived
   when the filename encodes a date, otherwise carried over from the previous
   manifest - so a date typed here survives the next regeneration.

   WORLD_V (in scripts/gen-world.mjs) appends ?v=N to every URL: bump it to bust
   the CDN/edge cache after replacing a photo, since /world/* isn't fingerprinted.

   PRIVACY: nothing is read from the image at runtime (no EXIF/GPS) - the date
   shown is only ever the \`taken\` value stored below.
   ============================================================ */
export const worldPhotos = [
${body}
];
`;

await writeFile(OUT, out);
const dated = rows.filter((r) => r.taken).length;
console.log(`Wrote ${rows.length} photos to src/worldData.js  (taken set on ${dated})`);
