export const profile = {
  name: 'Hemang Choudhary',
  role: 'B.Tech IT · Backend & ML systems',
  location: 'Jodhpur, IN',
  email: 'coehemang@gmail.com',
  altEmail: 'hemangc37@gmail.com',
  phone: '+91 8302 465 967',
  links: [
    { label: 'GitHub',   href: 'https://github.com/23f3001304' },
    { label: 'LinkedIn', href: 'https://linkedin.com/in/coehemang' },
  ],
};

export const intro = [
  'Engineer working on backend systems, ML pipelines, and the occasional weird side-project. Currently a B.Tech IT student at MBM University while parallel-tracking a B.S. in Data Science & AI at IIT Madras.',
  'Recently trained CycleGANs at DRDO Jodhpur, shipped a Pydantic-AI agent framework that scored 92/100 on adversarial evals, and wrote Git from scratch in Node because the manual was not enough.',
];

export const experience = [
  {
    role: 'Research Intern',
    org: 'Defence Research & Development Organisation',
    place: 'Jodhpur, IN',
    when: 'May → Jul 2025',
    bullets: [
      'Trained an image-to-image translation model (CycleGAN) for 50 epochs per experiment on 1,000+ paired & unpaired images using CUDA-accelerated GPU training.',
      'Evaluated outputs through qualitative comparisons every 5 epochs and tuned training parameters against observed artefacts and performance trends.',
    ],
  },
];

export const skills = [
  { label: 'Languages', items: ['Python', 'C', 'C++', 'Java', 'JavaScript', 'SQL', 'Kotlin'] },
  { label: 'Web',       items: ['React', 'Next.js', 'Node.js', 'Flask', 'Tailwind', 'HTML', 'CSS'] },
  { label: 'Data',      items: ['SQLite', 'MySQL', 'MongoDB'] },
  { label: 'Systems',   items: ['Linux', 'Git', 'POSIX', 'Docker'] },
  { label: 'Tools',     items: ['Heroku', 'GitHub', 'Figma'] },
];

export const education = [
  { school: 'MBM University, Jodhpur', degree: 'B.Tech, Information Technology', score: '7.8 / 10', when: '2023 → Present' },
  { school: 'IIT Madras, Chennai',     degree: 'B.S, Data Science & AI',          score: '8.0 / 10', when: '2023 → Present' },
];

export const certifications = [
  { name: 'Introduction to Software Development - Amazon (Coursera)', when: '2024' },
  { name: 'SQL Advanced - HackerRank',            when: '2024' },
  { name: 'JavaScript Intermediate - HackerRank', when: '2024' },
  { name: 'Intermediate SQL - DataCamp',          when: '2023' },
];

/* ============================================================
   Project detail records - one per /projects/:slug subpage.
   ============================================================ */
export const projects = [
  {
    id: 'PRJ-004',
    slug: 'typereal',
    name: 'TypeReal',
    tagline: 'A Monkeytype-class typing instrument - seven modes, a sub-16 ms engine, and a server-authoritative duel.',
    when: 'May 2026 → Present',
    status: 'LIVE',
    stack: ['React', 'TypeScript', 'Fastify', 'Prisma', 'Socket.IO'],
    metrics: [
      { value: '7',  unit: '',   label: 'test modes' },
      { value: '16', unit: 'ms', label: 'keystroke-to-pixel budget' },
      { value: '6',  unit: '',   label: 'built-in themes' },
      { value: '0',  unit: '',   label: 'signup to start typing' },
    ],
    accent: '#ff6b35',
    overview: [
      'TypeReal is a typing-speed trainer in the Monkeytype lineage, rebuilt around one obsession: the gap between a key going down and the glyph turning correct should never be felt. The whole front end is budgeted to keep that path under 16 ms - one frame at 60 Hz.',
      'It runs as a monorepo - a React + TypeScript client on Vite, and a Fastify API with Prisma, Lucia sessions, and Arctic OAuth. Guests type immediately; signing in unlocks history, a 1v1 duel, and a ghost that races your own best run.',
    ],
    sections: [
      {
        title: 'The typing surface',
        body: 'The interactive surface counts correct and error characters in refs rather than React state, so WPM and accuracy are exact on every keystroke instead of approximated from cursor position. The caret is a single absolutely-positioned bar that slides ~80 ms between cells and snaps on line wrap. Below 70% accuracy the run is marked failed - the WPM number is struck through and a quiet `test failed` badge appears instead of celebrating a bad result.',
        figure: { id: 'FIG 4.1', caption: 'The /test surface - seven modes, live WPM and accuracy, no signup.', src: '/projects/typereal/test.png', alt: 'TypeReal typing surface with mode pills, live stats, and a word passage' },
      },
      {
        title: 'Real-time duels and a ghost of your best run',
        body: 'A server-authoritative 1v1 duel puts the opponent\'s cursor on your passage in real time over Socket.IO - pick a track, create a private room, share the link. A ghost mode races you against your own fastest run on the exact same text. The seven solo modes (time, words, quote, zen, numbers, code across four languages, and paste-your-own custom) narrow to the four that make sense head-to-head.',
        figure: { id: 'FIG 4.2', caption: 'The duel lobby - private 1v1 rooms over a shared passage.', src: '/projects/typereal/duel.png', alt: 'TypeReal duel lobby with track and difficulty pills' },
      },
      {
        title: 'A theme system down to the token',
        body: 'Every colour is a `--tr-*` token - surfaces, foreground, borders, and semantic states all the way down to the opponent and ghost cursors. The editor sets each one against a live preview that types in solo, versus-opponent, and versus-ghost states at once, so a theme is judged on real passages rather than swatches. Six built-in themes ship; the custom editor unlocks for signed-in users.',
        figure: { id: 'FIG 4.3', caption: 'The theme editor - every token, with a live typing preview.', src: '/projects/typereal/themes-editor.png', alt: 'TypeReal theme token editor with color tokens and a live preview' },
      },
      {
        title: 'History, accounts, and the backend behind them',
        body: 'Signed-in users get every test logged - WPM, raw, accuracy, consistency, and time, filterable per mode. Behind it is a Fastify API issuing Lucia cookie sessions via magic-link email (single-use tokens hashed at rest, 10-minute TTL, rate-limited per route) and Google OAuth through Arctic with state-cookie CSRF protection. Account linking only trusts a verified Google email, token consumption is race-safe, and the whole surface is documented down to every secret it reads.',
        figure: { id: 'FIG 4.4', caption: 'History - every test, by mode, with per-run telemetry.', src: '/projects/typereal/history.png', alt: 'TypeReal history table of past tests with WPM and accuracy' },
      },
      {
        title: 'A landing page that types itself',
        body: 'The marketing page runs three live TypingDemo instances at once - a solo surface, a 1v1 duel with a second cursor racing 70 ms against 55 ms (scripted errors at characters 18 and 52), and a ghost demo that remaps `--tr-color-opponent` to `--tr-color-ghost` so the rival cursor reads as your past self. Stats under each panel update in tabular figures as the demo backspaces through its own mistakes, and the closing call-to-action runs a CharacterRain of falling glyphs over GSAP scroll reveals and Lenis smooth scroll.',
        figure: { id: 'FIG 4.5', caption: 'The landing page - a self-typing demo of the surface, duel, and ghost.', src: '/projects/typereal/landing.png', alt: 'TypeReal landing hero reading "Type fast. Type real." above a live typing demo' },
      },
      {
        title: 'Seven knobs for the typing surface',
        body: 'A floating ThemeWidget springs open into a tabbed tray whose Surface tab carries seven persisted controls - a text-size slider clamped 18-40 px with instant caret re-measure via ResizeObserver, left / center / right / justify alignment on a stroke-icon segmented control, compact / default / spacious density, a 2 / 3 / 4 / 5 / full lines limit, smooth-vs-instant caret, an easy-to-mixed difficulty picker, and a six-font grid (JetBrains Mono, IBM Plex Mono, Fira Code, Roboto Mono, Inter, System mono) live-applied through `--tr-font-passage`. Every value persists to localStorage; a drop-in custom-font upload stays locked behind sign-in.',
        figure: { id: 'FIG 4.6', caption: 'The Surface tray - size, density, caret, alignment, and font, live over a real passage.', src: '/projects/typereal/surface.png', alt: 'TypeReal surface customization panel with size, density, caret, alignment and font controls' },
      },
      {
        title: 'Code mode - four languages, two clocks',
        body: 'Code mode types real one-liners in javascript, python, rust, and go, with a lines-vs-time kind toggle: lines joins 5 / 10 / 20 snippets with real newlines and renders a return glyph per line, while time counts down 30 / 60 / 120 s. The Enter key actually types the newline, each line wraps on its own, and the sub-option pill row re-animates whenever you switch language or clock.',
        figure: { id: 'FIG 4.7', caption: 'Code mode - real multi-line snippets across four languages.', src: '/projects/typereal/code-mode.png', alt: 'TypeReal code mode typing a JavaScript snippet with newline glyphs' },
      },
      {
        title: 'One number, one chart, a fail state in red',
        body: 'Finishing a run springs in a result card: a 96 px WPM number over a hand-rolled SVG chart that plots per-second ticks sampled during the test - a solid wpm line, a dashed raw line, and red dots only on the seconds the cumulative error count rose. Drop below 70 % accuracy and the panel rings error-red, the WPM number is struck through, and a quiet "test failed" badge replaces the save / sign-up call to action instead of celebrating a bad run.',
        figure: { id: 'FIG 4.8', caption: 'The end-of-test result card and per-second WPM chart.', src: '/projects/typereal/result.png', alt: 'TypeReal result card with a large WPM number and a WPM-over-time chart' },
      },
    ],
    conclusion: [
      'TypeReal began as a Monkeytype clone and turned into an argument that the clone is the easy part. The work went where it usually gets skipped: the input loop budgeted to a single 16 ms frame, WPM and accuracy counted exactly from refs instead of estimated off the cursor, and a 1v1 duel made server-authoritative so an opponent\'s run can\'t be forged.',
      'It stays honest about the line between guest and account - anyone types immediately, and history, duels, the ghost, and the custom theme editor unlock the moment you sign in. The result reads less like a typing test than a typing instrument: every knob persisted, every result either earned or struck through in red.',
    ],
    figma: null,
    links: [
      { label: 'Website', href: 'https://typereal.coehemang.dev' },
      { label: 'GitHub',  href: 'https://github.com/23f3001304' },
    ],
  },
  {
    id: 'PRJ-005',
    slug: 'formdash',
    name: 'Formdash',
    tagline: 'A form builder where the branching actually holds - one rule engine, enforced in three places.',
    when: 'May 2026',
    status: 'LIVE',
    stack: ['React', 'Express', 'Prisma', 'PostgreSQL', 'Tailwind'],
    metrics: [
      { value: '24', unit: '',  label: 'field & display block types' },
      { value: '44', unit: '',  label: 'API tests, ~450 ms' },
      { value: '3',  unit: '',  label: 'contexts, one rule engine' },
      { value: '7',  unit: '+', label: 'anti-abuse guards' },
    ],
    accent: '#5c7cfa',
    overview: [
      'Formdash takes the boring parts of forms seriously: branching that holds, responses that can\'t be forged, and uploads that are what they claim to be. You drag questions onto a canvas, wire up show/hide rules, publish to a public URL, and watch responses land with per-question analytics.',
      'It is a pnpm monorepo - a React 19 client on Vite with Tailwind v4 and shadcn primitives, and an Express API on Prisma. The web tier deploys to Cloudflare Pages, the API to Heroku with Postgres, and files go to any S3-compatible bucket through one storage driver.',
    ],
    sections: [
      {
        title: 'A builder that previews itself',
        body: 'The editor is drag-and-drop over dnd-kit, with 18 question types and 6 display blocks, a live preview, and per-form theming. Drafts persist through a dedicated Web Worker that owns IndexedDB - the UI never touches the network directly, so autosave and offline edits stay smooth, and the old localStorage store migrates itself on first run.',
        figure: { id: 'FIG 5.1', caption: 'The drag-and-drop editor with live preview.', src: '/projects/formdash/editor-build.png', alt: 'Formdash drag-and-drop form editor' },
      },
      {
        title: 'One rule engine, three contexts',
        body: 'Conditional logic - nested AND/OR groups over eq / neq / gt / lt / contains - is written once in a shared package and evaluated in three places: the editor preview, the public runtime, and the server. The last one matters. A respondent can POST straight to `/submit` and skip the UI, so the server re-evaluates visibility and only requires answers to questions that were actually shown.',
        figure: { id: 'FIG 5.2', caption: 'Branching rules in the editor, mirrored server-side.', src: '/projects/formdash/editor-logic.png', alt: 'Formdash conditional logic editor' },
      },
      {
        title: 'Responses, analytics, and an API',
        body: 'Owners get a filtered responses list, per-question charts in Recharts, CSV export, HMAC-signed webhooks, and personal access tokens for a public REST API. Each form carries its own constraints - password gating, a response cap, a close date, and optional geolocation gated behind explicit consent.',
        figure: { id: 'FIG 5.3', caption: 'Per-question analytics for a live form.', src: '/projects/formdash/analytics.png', alt: 'Formdash response analytics dashboard' },
      },
      {
        title: 'Anti-abuse and the file path',
        body: 'Public endpoints sit behind layered rate limits (per-IP, per-form-and-IP, per-token), a honeypot, timing checks, and payload size and nesting caps. Uploads are validated by MIME and magic bytes, not just extension, and webhook delivery runs through an SSRF guard so a hostile target URL can\'t reach internal hosts. 44 vitest specs cover the guards, the webhook HMAC round-trip, and the rate-limit math.',
        figure: { id: 'FIG 5.4', caption: 'The public form runtime a respondent sees.', src: '/projects/formdash/public-form.png', alt: 'Formdash public form runtime' },
      },
      {
        title: 'Projects, not a flat list of forms',
        body: 'Every form lives inside a project, so the dashboard opens on a project pane with a live KPI line over one row per form - question count, response count, a Draft / Live / Closed status dot, and a relative "updated" time. A per-row menu handles rename, duplicate, move-to-project, copy public link, and a guarded delete; the active project rides in `?project=` so the view is shareable and survives reloads. Response counts refresh on an 8-second background poll into the data worker, so a new submission shows up without a manual refresh.',
        figure: { id: 'FIG 5.5', caption: 'The projects workspace - a live forms-and-responses overview.', src: '/projects/formdash/dashboard.png', alt: 'Formdash dashboard listing the forms in a project with status dots and response counts' },
      },
      {
        title: 'A per-form design system, not a colour picker',
        body: 'Design mode ships four full presets - Forest, Ink, Midnight, Sunrise - each a complete theme (palette, type, density, radius) that swaps the document wholesale, then exposes six editable colour tokens, three densities, three corner radii, and four type pairings. Every change repaints a real respondent preview in the centre pane - the same render path the public form uses - and themes ride onto the live form as `--p-*` custom properties rather than hardcoded styles.',
        figure: { id: 'FIG 5.6', caption: 'Design mode - a preset, a live themed preview, and per-token controls.', src: '/projects/formdash/editor-design.png', alt: 'Formdash editor in Design mode with theme presets and a live preview' },
      },
      {
        title: 'Four ways through a form',
        body: 'Flow mode picks how respondents move: single page, paginated with Next / Back, vertical scroll, or a horizontal snap one question per panel - and the snap modes add a scroll-by-question-vs-section toggle. The progress indicator is its own axis with four styles (none / bar / dots / N-of-M), as is question numbering, with ten formats from 01. to Roman, lettered, #3, and Q3, and statements or media never numbered. The centre pane is the live interactive preview, so the feel is verified before anything ships.',
        figure: { id: 'FIG 5.7', caption: 'Flow mode - navigation model, progress, and numbering over a live preview.', src: '/projects/formdash/editor-flow.png', alt: 'Formdash editor in Flow mode showing navigation, progress and numbering options' },
      },
      {
        title: 'Publish: a slug, a QR, and a way back',
        body: 'Publishing is a popover, not a wizard: set a public slug (live-previewed as /f/your-slug), hit publish, and the form goes live with a copy-link row, an open-in-new-tab affordance, and a QR card rendered through qrcode.react that exports a 512 px PNG. Double-clicks are guarded with an in-flight pending state so a slow network cannot race the snapshot, and Settings rounds it out with a response cap, a close-at datetime, a shared-password gate, redirect-on-submit, and an iframe embed for anonymous forms.',
        figure: { id: 'FIG 5.8', caption: 'The publish popover - slug, public URL, copy link, and a downloadable QR.', src: '/projects/formdash/publish-popover.png', alt: 'Formdash publish popover with a public slug, URL, copy button and QR code' },
      },
      {
        title: 'Responses read like filled-in forms',
        body: 'The responses surface is master-detail, not a wide spreadsheet: a list on the left, the full submission rendered as a readable filled-in form on the right. A filter strip composes a date range, respondent type (anyone / signed-in / anonymous), a with-location toggle, and free-text search across answers, email, and timezone - and the question-aware filters reuse the exact same evaluateConditional engine as the branching rules. The header reads "12 of 47 submissions" as filters narrow, Export CSV always streams the current view, and live submissions poll in every 5 seconds.',
        figure: { id: 'FIG 5.9', caption: 'The responses inbox - a filterable list beside the full filled-in response.', src: '/projects/formdash/responses.png', alt: 'Formdash responses page with a filter strip, a submission list and one rendered response' },
      },
      {
        title: 'Templates: start from curated, save your own',
        body: 'The gallery ships 15 starter templates across Feedback, Growth, Ops, Internal, and Hiring, each carrying a real question list - the research template alone seeds 11 questions across statement, scale, checkbox, and long-text. Clicking one clones it into the active project; cards show a category, an icon, and an exact question count. A six-strong anime pack ships its own palette, typography, and inline SVG background for instant identity, and any form you build can be saved back as a reusable template under the "Yours" tab.',
        figure: { id: 'FIG 5.10', caption: 'The templates gallery - 15 curated starters plus an anime pack, each cloneable.', src: '/projects/formdash/templates.png', alt: 'Formdash templates gallery grid with categories, icons and question counts' },
      },
    ],
    conclusion: [
      'Formdash is built on a single distrust: a form builder is only as good as the parts nobody demos. The rule engine behind branching is written once and run in three places - editor, public runtime, and server - and the server is the one that counts, re-evaluating visibility so a hand-rolled POST can\'t answer a question it was never shown.',
      'Around that sit the unglamorous guarantees - layered rate limits, magic-byte upload checks, an SSRF-guarded webhook path, and 44 specs holding them in place. The surface on top - projects over a flat list, a per-form design system, four ways through a form, responses that read like filled-in forms - is the easy half; the half that matters assumes every request is hostile until it proves otherwise.',
    ],
    figma: null,
    links: [
      { label: 'Website', href: 'https://formdash.coehemang.dev' },
      { label: 'GitHub',  href: 'https://github.com/23f3001304' },
    ],
  },
  {
    id: 'PRJ-001',
    slug: 'quizzy',
    name: 'Quizzy',
    tagline: 'An autonomous agent that solves a quiz end to end - a fast planner, a tool-using solver, and a sandbox that runs its own code.',
    when: 'Nov → Dec 2025',
    status: 'SHIPPED',
    stack: ['FastAPI', 'Pydantic AI', 'Gemini 2.5', 'Docker'],
    metrics: [
      { value: '90', unit: '',     label: 'tools, 12 modules' },
      { value: '2',  unit: '',     label: 'agents: plan + solve' },
      { value: '5',  unit: '',     label: 'FastAPI endpoints' },
      { value: '92', unit: '/100', label: 'graded eval score' },
    ],
    sprite: '/oneko/oneko-tora.gif',
    accent: '#ff5e00',
    overview: [
      'Quizzy is the answer side of a quiz: point it at a starting URL and it solves question after question on its own. A FastAPI service takes the URL, spawns a background task, and runs a two-agent loop - a fast Gemini Flash agent sketches a strategy, then a Gemini Pro agent solves with tools and returns a typed answer that gets submitted automatically.',
      'Most of the work is the harness around the model: 90 tools across twelve modules (web, data, documents, media, math), a subprocess sandbox that runs Python the agent writes on the fly, and a self-correcting loop that feeds each rejection back into the next attempt. Everything that crosses a layer is a Pydantic contract, and the whole thing containerises into one image.',
    ],
    sections: [
      {
        title: 'One URL becomes a whole quiz',
        body: 'Quizzy solves a quiz the way a person would walk it: load the page, work out the answer, submit, and follow the link to the next question. The whole run is one `while` loop in `QuizSolver`. Each turn fetches the page, plans, solves, and submits; a correct answer with a `next_url` advances the chain, a correct answer without one ends it, and a wrong answer drops into a retry. None of it blocks the caller - `/start` checks the secret and hands the loop to a FastAPI background task.',
        blocks: [
          { kind: 'diagram', id: 'solve-loop', caption: 'The autonomous loop: fetch, plan, solve, submit, then chain or retry.' },
          { kind: 'code', lang: 'py', caption: 'solver.py · the chain loop (condensed)', code: [
            '# walk the question chain until a question has no next_url',
            'while True:',
            '    result = await self._solve_single_question(context)   # fetch -> plan -> solve -> submit',
            '',
            '    if result.correct and result.next_url:',
            '        context.current_url = result.next_url             # advance to the next question',
            '        context.attempt_number = 0',
            '    elif result.correct:',
            '        break                                             # no next_url -> the quiz is done',
            '    else:',
            '        context.last_failure_reason = result.message      # remember why, then retry',
            '        if context.attempt_number >= MAX_RETRIES:',
            '            break',
            '        context.attempt_number += 1',
          ] },
        ],
      },
      {
        title: 'Plan first, then solve',
        body: 'Two agents split the work. A cheap Gemini Flash `guidance_agent` reads the question and writes a short strategy - which files to open, what format the answer needs, the usual traps. That strategy is folded into the prompt for the Gemini Pro `quiz_agent`, which does the real solving with tools and is constrained to return a `QuizAnswer`, not free text. Pydantic-AI validates that shape before the answer is ever submitted.',
        blocks: [
          { kind: 'diagram', id: 'two-agents', caption: 'A fast planner feeds a strategy to the tool-using solver, which returns a typed answer.' },
          { kind: 'code', lang: 'py', caption: 'prompts.py · two agents, two models', code: [
            '# fast planner: cheap model, no tools, returns a strategy string',
            'guidance_agent = Agent(',
            '    model=GoogleModel("gemini-2.5-flash", provider=provider),',
            '    output_type=str,',
            '    system_prompt=GUIDANCE_PROMPT,',
            ')',
            '',
            '# solver: stronger model, typed output, tools registered below',
            'quiz_agent = Agent(',
            '    model=GoogleModel("gemini-2.5-pro", provider=provider),',
            '    deps_type=QuizDependencies,',
            '    output_type=QuizAnswer,        # Pydantic-validated, not free text',
            '    system_prompt=SYSTEM_PROMPT,',
            '    retries=2,',
            ')',
          ] },
        ],
      },
      {
        title: 'A tool for every file type',
        body: 'The solver carries 90 tools across twelve modules - web scraping, JSON and CSV and XML, PDFs and spreadsheets and archives, audio and video and image OCR, hashing, regex, symbolic math. Many of them are thin by design: the tool downloads the file, writes a few lines of Python, and runs them in a subprocess sandbox with a timeout, then hands back stdout. That keeps heavy libraries like pdfplumber and ffprobe out of the request process and gives every risky operation its own bounded, disposable runtime.',
        blocks: [
          { kind: 'diagram', id: 'tool-belt', caption: 'Tools grouped by modality; the file-heavy ones run generated Python in the sandbox.' },
          { kind: 'code', lang: 'py', caption: 'unified.py · a tool that writes and runs its own code', code: [
            '@quiz_agent.tool',
            'async def process_document(ctx, url: str) -> str:',
            '    path = await sandbox.download_file(url)',
            '    # emit a pdfplumber snippet, then run it in the sandbox',
            '    code = f"import pdfplumber; print(pdfplumber.open(r\'{path}\').pages[0].extract_text())"',
            '    out = await sandbox.execute_code(code, timeout=120)   # python subprocess + timeout',
            '    return out.stdout if out.success else out.stderr',
          ] },
        ],
      },
      {
        title: 'Wrong answer? Read the feedback, try again',
        body: 'A wrong answer is not a dead end. When the quiz server rejects a submission it usually says why, and that reason - together with the exact answer that was rejected - gets written straight into the next prompt under a loud retry banner. The agent reads its own miss before trying again, up to a per-question cap, which turns most format mistakes (a date with a stray time, an array where the schema wanted an object) into a second-attempt fix.',
        blocks: [
          { kind: 'code', lang: 'py', caption: 'solver.py · the self-correcting retry', code: [
            '# on a wrong answer, the rejection becomes part of the next prompt',
            'if context.attempt_number > 0:',
            '    retry_note = (',
            '        "PREVIOUS ANSWER WAS WRONG: " + context.last_wrong_answer + "\\n"',
            '        "SERVER FEEDBACK: " + context.last_failure_reason + "\\n"',
            '        "Your new answer MUST be different from the one above."',
            '    )',
            '    prompt = build_prompt(page, guidance, retry_note)   # the model sees its own miss',
          ] },
        ],
      },
      {
        title: 'Typed at every edge, built to never hang',
        body: 'Everything that crosses a layer is a Pydantic model - `QuizContext` for session state, `QuizDependencies` for what tools may touch, `QuizAnswer` for the model\'s output, `QuizResult` for what gets recorded. The contracts double as guardrails: the agent cannot hand back a shape the rest of the code does not expect. And when the model fails outright, the loop does not stall - a regex fallback covers the common question types, and an emergency submit fires a placeholder just to pull back a `next_url` and keep the chain moving.',
        blocks: [
          { kind: 'code', lang: 'py', caption: 'models.py + solver.py · typed output, never hang', code: [
            'class QuizAnswer(BaseModel):                  # the agent must return THIS shape',
            '    answer: Any = Field(..., description="the computed answer")',
            '    submission_url: str',
            '    confidence: float = Field(default=1.0, ge=0.0, le=1.0)',
            '    reasoning: str = ""',
            '',
            '# if the agent throws, do not hang the chain - submit a fallback, keep going',
            'async def _emergency_submit(self, context) -> QuizResult:',
            '    resp = await action.submit_answer(endpoint=base + "/submit",',
            '                                      answer="error_fallback", ...)',
            '    return QuizResult(correct=resp.correct, next_url=resp.url, ...)',
          ] },
        ],
      },
    ],
    conclusion: [
      'Quizzy is less a quiz solver than a small autonomous-agent harness with a quiz for a target. The model is one component; the engineering around it - plan then solve, a typed contract on every edge, a sandbox for code the agent writes itself, and a retry loop that feeds failures back in - is what lets it finish a chain it has never seen.',
      'The shape generalises past quizzes. Swap the page fetcher and the submit step and the same loop drives any task that is read, decide, act, observe, repeat. What is here is the part that is hard to fake: bounded execution, structured output, and a recovery path for every place the model can go wrong.',
    ],
    figma: null,
    links: [
      { label: 'GitHub', href: 'https://github.com/23f3001304' },
    ],
  },
  {
    id: 'PRJ-002',
    slug: 'animy',
    name: 'ANIMY',
    tagline: 'A prompt becomes an animation - an LLM writes Manim, four workers render it, and the browser polls a status map for progress.',
    when: 'Feb → Aug 2025',
    status: 'COMING SOON',
    stack: ['React', 'Node.js', 'Gemini', 'Manim', 'Cloudflare R2', 'Heroku'],
    metrics: [
      { value: '4',  unit: '',  label: 'concurrent render workers' },
      { value: '30', unit: 's', label: 'Heroku router ceiling' },
      { value: '3',  unit: '',  label: 'self-healing render retries' },
      { value: '2',  unit: '',  label: 'real-time strategies tried' },
    ],
    sprite: '/oneko/oneko-vaporwave.gif',
    accent: '#8a5cff',
    overview: [
      'ANIMY turns a sentence into a short animation. The prompt goes to a language model that writes Manim, the Python animation engine; the server renders that code headlessly into an mp4 and stores the result. The frontend is React - this case study is the Node tier, where one request has to survive a render that takes minutes.',
      'The spine is small: four workers drain a queue, each running the model-then-render pipeline out of band, while the browser tracks progress by polling a status endpoint. That channel was shaped by two separate constraints - WebSockets cost too much to hold open for every user, and Heroku\'s 30-second request limit ruled out any poll that waits with the connection open - so what is left is short polls that each return a quick status.',
    ],
    sections: [
      {
        title: 'Prompt in, animation out',
        body: 'ANIMY turns a sentence into a short animation. The prompt goes to Gemini 2.5 Pro under a system prompt that pins it to Manim, the Python animation engine; the model returns Python, the server writes it to a file and renders it headlessly with `manim -qm`, ffmpeg lifts a thumbnail off the result, and the mp4, thumbnail, and source all land in Cloudflare R2. Each stage updates a status record so the client can narrate what is happening.',
        blocks: [
          { kind: 'diagram', id: 'animy-pipeline', caption: 'A prompt becomes Manim code, renders to an mp4, and is stored in R2.' },
          { kind: 'code', lang: 'js', caption: 'aiService.js · the model writes Manim, then it renders', code: [
            '// the model returns Manim (Python) for the prompt',
            'const res = await ai.models.generateContent({',
            '  model: "gemini-2.5-pro",',
            '  contents: `Give only the Python code for: ${prompt}`,',
            '  config: { temperature: 0.1, systemInstruction: systemPrompt },',
            '});',
            'const code = extractPython(res.text);      // pull it out of the code block',
            'fs.writeFileSync(`temp/${id}.py`, code);',
            '',
            '// render headlessly; ffmpeg then grabs a thumbnail off the mp4',
            'exec(`manim -qm temp/${id}.py Anim_script --media_dir video`, (err) => {',
            '  // -> video/videos/<id>/720p30/Anim_script.mp4, then upload to R2',
            '});',
          ] },
        ],
      },
      {
        title: 'Four workers and an instant reply',
        body: 'A render is slow, so the request that starts one cannot wait for it. `POST /generate` validates the prompt, hands the job to a worker if one of four slots is free or pushes it onto a queue, and replies right away with the chat id and a status. The render runs outside the request: each worker is fire-and-forget, and when it settles it frees its slot and pulls the next job off the queue. A bounded pool keeps a burst of prompts from swamping the box, and an `AbortController` per worker makes a job killable mid-render.',
        blocks: [
          { kind: 'diagram', id: 'animy-workers', caption: 'Generate replies at once; four workers drain the queue, each pulling the next job as it frees up.' },
          { kind: 'code', lang: 'js', caption: 'videoController.js · accept the job, reply at once', code: [
            'const MAX_CONCURRENT_TASKS = 4;',
            'const queue = [];',
            'const activeWorkers = new Map();',
            '',
            'function generateVideo(req, res) {',
            '  const { prompt, userId, chatId } = req.body;',
            '  const task = { prompt, userId, chatId };',
            '',
            '  if (activeWorkers.size < MAX_CONCURRENT_TASKS) startWorker(task); // slot free',
            '  else { queue.push(task); updateChatStatus(userId, chatId, "queued"); }',
            '',
            '  // reply now - the render does NOT run inside this request',
            '  res.json({ userId, chatId, status: activeWorkers.size < 4 ? "processing" : "queued" });',
            '}',
            '',
            'function startWorker(task) {',
            '  const ctrl = new AbortController();',
            '  processVideoGeneration(task, ctrl.signal)                 // non-blocking',
            '    .finally(() => { activeWorkers.delete(task.id); processNextTasks(); });',
            '}',
          ] },
        ],
      },
      {
        title: 'WebSockets, polling, and Heroku\'s 30-second router',
        body: 'Progress needs to reach the browser somehow. WebSockets were the obvious first reach, but they are expensive for this: a warm connection held open for every user, plus the heartbeats, connection state, and reconnection handling that come with it - a lot of standing cost for a job whose real work is the render, not the transport. So the design went with polling instead. That is where Heroku bit: its router kills any request that goes 30 seconds without a first byte (an H12 timeout), so a poll that holds the connection open waiting for the job to move gets cut off mid-wait. The fix was to make every status return at once. Each worker writes progress to an in-memory map keyed by user and chat, and the client polls a status endpoint on an interval that answers in milliseconds with whatever the current state is. Nothing is held open, so the 30-second limit never comes up.',
        blocks: [
          { kind: 'diagram', id: 'animy-poll', caption: 'A held-open request dies at the 30s wall; short polls of a status map never get close.' },
          { kind: 'code', lang: 'js', caption: 'statusService.js · progress is a map the client polls', code: [
            '// progress lives in a plain in-memory map, keyed by user + chat',
            'const chatStatus = {};',
            'function updateChatStatus(userId, chatId, status, message, details = {}) {',
            '  chatStatus[`${userId}:${chatId}`] = {',
            '    status, message, lastUpdate: new Date().toISOString(), ...details,',
            '  };',
            '}',
            '',
            '// the client short-polls THIS; each call is a fast map lookup',
            'function getVideoStatus(req, res) {',
            '  const { userId, chatId } = req.params;',
            '  const status = getChatStatus(userId, chatId);',
            '  if (!status) return res.status(404).json({ error: "Chat not found" });',
            '  res.json({ status });   // queued | processing | rendering | uploading | complete',
            '}',
          ] },
        ],
      },
      {
        title: 'When the render breaks, the model fixes it',
        body: 'Model-written code does not always run. When Manim exits with a Python traceback, the server does not give up - it lifts the error box out of stderr, feeds it back to Gemini along with the failing code, and re-renders, up to three times before it reports a failure. The status flips to `fixing` so the browser can say so. It is a small loop, but it turns most first-try syntax slips into a finished video instead of an error.',
        blocks: [
          { kind: 'code', lang: 'js', caption: 'aiService.js · a render error loops back to the model', code: [
            'exec(`manim -qm ${file} Anim_script --media_dir video`, async (err, stdout, stderr) => {',
            '  if (stderr.includes("Traceback") && retryCount < maxRetries) {  // Manim rejected it',
            '    retryCount++;',
            '    updateChatStatus(userId, chatId, "fixing", `Fix attempt ${retryCount}/${maxRetries}`);',
            '    const errorMessage = extractErrorMessage(stderr);            // lift the traceback out',
            '    const fixPrompt = `This threw:\\n${errorMessage}\\nFix it. Previous code:\\n${code}`;',
            '    return resolve(await generateManimCode(fixPrompt, userId, chatId, filename));',
            '  }',
            '  // otherwise the mp4 is ready - upload it to R2',
            '});',
          ] },
        ],
      },
    ],
    conclusion: [
      'The shape of ANIMY falls out of one fact: a render outlives any HTTP request you are allowed to hold open. Once you accept that, the rest follows - take the job, return an id, run the work on a bounded pool, and let the client poll a cheap status endpoint. WebSockets lost on cost, and Heroku decided how that polling had to behave: return fast, hold nothing open.',
      'The simplicity is deliberate. Progress is a plain object, not Redis; the queue is an array, not a broker. On a single web dyno that is enough, and it keeps the whole status path down to a map lookup. Spread across several dynos the map would have to move somewhere shared - the same decision, made again against a new constraint.',
    ],
    figma: null,
    links: [
      { label: 'Website', href: '#' },
    ],
  },
  {
    id: 'PRJ-007',
    slug: 'spider-man',
    name: 'Spider-Man',
    tagline: 'A concept promo site for Spider-Man: Into the Spider-Verse - chromatic display type, a Marvel marquee, and glassmorphism over Miles Morales art. Designed in Figma.',
    when: '2025',
    status: 'DESIGN',
    stack: ['Figma', 'UI Design', 'Web Design', 'Glassmorphism'],
    metrics: [
      { value: '4', unit: '',  label: 'nav destinations' },
      { value: '4', unit: '',  label: 'reusable components' },
      { value: '3', unit: '',  label: 'holographic color stops' },
      { value: '1', unit: '',  label: 'shared design system' },
    ],
    sprite: '/oneko/oneko-maia.gif',
    accent: '#e23636',
    overview: [
      'Spider-Man is a concept landing site for Into the Spider-Verse, designed end to end in Figma. The brief I set myself: catch the film\'s comic-book energy without the layout turning into noise. The answer was a tight system - one loud red, a chromatic display face for the title, and clean glass panels that let the character art carry the page.',
      'The work spans a hero, a details view, and a shared asset board that pins down the marquee, the mini character card, the button, and the color tokens. Everything keys off a single palette, so the Home and Details screens read as one product rather than two posters.',
    ],
    sections: [
      {
        title: 'The hero',
        body: 'The landing page leads with the title set in a chromatic display face - a green-to-pink-to-blue split that mimics the 3D-glasses misregistration that is the film\'s signature look. A Marvel-and-Sony release badge sits above it, a Miles Morales render anchors the right, and a glass character card introduces him without crowding the art. Two calls to action, watch the trailer and book a ticket, keep the goal obvious.',
        figure: { id: 'FIG 7.1', caption: 'The landing hero - chromatic title, Miles Morales art, and the book-a-ticket call to action.', src: '/projects/spider-man/home.png', alt: 'Spider-Man Into the Spider-Verse concept landing hero with a holographic title and Miles Morales artwork' },
      },
      {
        title: 'Details and the multiverse',
        body: 'The details view trades the hero for content: a Marvel marquee runs across the top, and glassmorphism panels - blurred, semi-transparent, lightly bordered - float over a full-bleed Miles render. Each panel introduces a piece of the world, the Spider-Verse itself and the line-up of spiders, while the frosted surface keeps the text legible over a busy image.',
        figure: { id: 'FIG 7.2', caption: 'The details view - glass panels over full-bleed character art.', src: '/projects/spider-man/details.png', alt: 'Spider-Man details page with glassmorphism cards over Miles Morales artwork' },
      },
      {
        title: 'The asset board',
        body: 'Behind the screens is one asset board that keeps them consistent. It fixes the marquee, the mini character card, the button, and the body surface, and names the palette: a black button, a crimson body, and the green-pink-blue trio that drives the holographic type. Designing the system first meant the Home and Details screens could be assembled from the same parts rather than restyled one at a time.',
        figure: { id: 'FIG 7.3', caption: 'The asset board - marquee, character card, button, and the color tokens in one place.', src: '/projects/spider-man/assets.png', alt: 'Spider-Man design system board showing the marquee, character card, color palette and display type' },
      },
    ],
    conclusion: [
      'Spider-Man is a study in restraint over a loud theme: one red, one chromatic accent, and a glass surface that lets the character art do the shouting. Building the asset board before the pages is what kept a comic-book brief from turning into clutter.',
    ],
    figma: null,
    links: [
      { label: 'Figma', href: 'https://www.figma.com/design/Ya9h0EYaw4uVjQngBwD6dM/Spider-man?node-id=0-1' },
    ],
  },
  {
    id: 'PRJ-008',
    slug: 'stic',
    name: 'STIC',
    tagline: 'A brand and landing-page design for the Student Tech Innovation Council - a red-and-cream editorial system, a numbered section grid, and a full social asset kit. Designed in Figma.',
    when: '2025',
    status: 'DESIGN',
    stack: ['Figma', 'Branding', 'Design System', 'Web Design'],
    metrics: [
      { value: '500', unit: '+', label: 'council members' },
      { value: '8',   unit: '',  label: 'landing sections' },
      { value: '2',   unit: '',  label: 'cohorts' },
      { value: '3',   unit: '',  label: 'launch tracks' },
    ],
    sprite: '/oneko/oneko-classic.gif',
    accent: '#c0463a',
    overview: [
      'STIC is the brand and web design for the Student Tech Innovation Council at M.B.M. University, Jodhpur. It is a reboot: a clearer identity, a warm red-on-cream palette, and a confident wordmark, built to make a new student council look like it has been around for years.',
      'The centerpiece is a long landing page that reads like an editorial spread - large roman-numeral sections walking through the vision, the cohorts, the projects, and the resources - backed by a kit of social templates for events, announcements, and milestones that keep every post on-brand.',
    ],
    sections: [
      {
        title: 'The opening screen',
        body: 'The landing page opens on one line that does the whole pitch at once: "Empowering you [to] become a better developer," with square and angle brackets borrowed from code so a tech audience reads the intent on sight and the final word lands in the brand red. Learn more and join now anchor the corners, the checkerboard motif frames the cream field, and the member marquee runs along the bottom. It says what STIC is for before any section has to explain it.',
        figure: { id: 'FIG 8.1', caption: 'The opening screen - a code-styled headline, two calls to action, and the member marquee.', src: '/projects/stic/hero.jpg', alt: 'STIC landing hero with the headline empowering you to become a better developer and learn more and join now buttons' },
      },
      {
        title: 'The landing page',
        body: 'The landing page is built like an editorial spread. A live marquee across the top carries the council\'s scale - five hundred-plus members, the next cohort, the live event - and below it large roman numerals walk through the story: the vision, the cohorts, the gauntlet, the network, the projects, the workshops, and the resources. The red-and-cream grid and the oversized section numbers give a young council the weight of an established one.',
        figure: { id: 'FIG 8.2', caption: 'The landing page - a numbered editorial grid from the vision through to resources.', src: '/projects/stic/landing.jpg', alt: 'STIC landing page with a member marquee and a numbered editorial section grid' },
      },
      {
        title: 'Insights and footer',
        body: 'Lower down, a dark insights band breaks the red with quotes from the team, then the footer does the practical work: a newsletter signup, a contact block with the council\'s email and campus address, and the STIC wordmark sitting over the navigation. It closes the page on identity rather than trailing off.',
        figure: { id: 'FIG 8.3', caption: 'Team insights, newsletter signup, and the contact footer.', src: '/projects/stic/landing-2.jpg', alt: 'STIC landing page footer with team insights, a newsletter signup and contact details' },
      },
      {
        title: 'The social asset kit',
        body: 'The brand reaches past the site into a kit of social templates: event announcements for the workshop tracks, logo lockups in every arrangement the wordmark needs, and status cards for updates, response times, and seat alerts. The checkerboard motif and the red-on-cream palette carry across all of them, so a feed of STIC posts reads as one identity.',
        figure: { id: 'FIG 8.4', caption: 'The social asset kit - event cards, announcements, and logo lockups.', src: '/projects/stic/assets.png', alt: 'STIC social media asset kit with event cards, announcements and logo lockups' },
      },
    ],
    conclusion: [
      'STIC is identity work as much as layout: a consistent red-and-cream system, an editorial grid, and a social kit that together make a brand-new council look settled and credible. The design language holds from a full landing page down to a single announcement card.',
    ],
    figma: null,
    links: [
      { label: 'Figma', href: 'https://www.figma.com/design/pZahn4aJCTORKyNVwbLMk3/STIC_WEBSITE?node-id=215-2' },
    ],
  },
  {
    id: 'PRJ-003',
    slug: 'build-my-own-git',
    name: 'Build My Own Git',
    tagline: 'Git\'s plumbing rebuilt on Node built-ins alone - a content-addressed object store the real git can still read.',
    when: 'Dec 2024 → Feb 2025',
    status: 'ARCHIVED',
    stack: ['Node.js', 'SHA-1', 'zlib', 'Buffer'],
    metrics: [
      { value: '0',  unit: '', label: 'runtime dependencies' },
      { value: '3',  unit: '', label: 'object types rebuilt' },
      { value: '40', unit: '', label: 'hex chars per address' },
      { value: '8',  unit: '', label: 'plumbing commands' },
    ],
    sprite: '/oneko/oneko-dog.gif',
    accent: '#10a37f',
    overview: [
      'Build Your Own Git, taken at the plumbing layer: not a wrapper over the `git` binary but a re-implementation of the thing underneath it, the content-addressed object store. Every file, directory, and commit becomes an object named by the SHA-1 of its own contents and written, zlib-deflated, under `.git/objects`.',
      'It runs on Node built-ins alone - `crypto` for SHA-1, `zlib` for framing, `fs` for the store - and stays close enough to the real format that `git cat-file` reads back the blobs, trees, and commits it produces. A small command-pattern CLI sends each verb to its own class.',
    ],
    sections: [
      {
        title: 'Every object is named by its own hash',
        body: 'The idea the whole thing rests on: an object\'s name is the SHA-1 of its own content. Git frames each object as a type, a byte length, a NUL byte, then the raw body, hashes that envelope, and writes it to `.git/objects/<first two hex>/<remaining 38>`, zlib-deflated. The two-character directory is a fan-out, so a repository never drops a million objects into one folder. `hash-object` is the smallest command that runs the full loop, and every other write command reuses it.',
        blocks: [
          { kind: 'diagram', id: 'content-address', caption: 'How a blob\'s bytes become an address and a path on disk.' },
          { kind: 'code', lang: 'js', caption: 'hash-write.js', code: [
            '// blob = a type, a byte length, a NUL, then the raw file',
            'const content = `blob ${size}\\0${fs.readFileSync(file)}`;',
            'const sha = crypto.createHash("sha1").update(content).digest("hex");',
            '',
            '// fan-out: .git/objects/<first 2>/<remaining 38>, stored deflated',
            'const dir = `.git/objects/${sha.slice(0, 2)}`;',
            'fs.mkdirSync(dir, { recursive: true });',
            'fs.writeFileSync(`${dir}/${sha.slice(2)}`, zlib.deflateSync(content));',
          ] },
        ],
      },
      {
        title: 'A directory folds into a Merkle tree',
        body: '`write-tree` walks the working directory depth-first. Files turn into blobs; directories turn into tree objects whose entries are `<mode> <name>\\0` followed by the child\'s hash packed as twenty raw bytes, not the forty hex characters you usually see. Because a tree\'s hash depends on its children\'s hashes, a snapshot is a Merkle tree: change one byte in one file and every hash from that file up to the root changes with it. The walk is post-order out of necessity - a parent cannot name a child it has not hashed yet.',
        blocks: [
          { kind: 'diagram', id: 'merkle', caption: 'A commit points at a tree that names blobs and sub-trees by hash.' },
          { kind: 'code', lang: 'js', caption: 'write-tree.js (condensed)', code: [
            'function walk(dir) {',
            '  const entries = [];',
            '  for (const name of fs.readdirSync(dir)) {',
            '    if (name === ".git") continue;',
            '    const full = path.join(dir, name);',
            '    if (fs.statSync(full).isDirectory()) {',
            '      entries.push({ mode: "40000",  name, sha: walk(full) });       // sub-tree',
            '    } else {',
            '      entries.push({ mode: "100644", name, sha: writeBlob(full) });  // blob',
            '    }',
            '  }',
            '  // each entry: "<mode> <name>\\0" + the child hash as 20 raw bytes',
            '  const body = entries.reduce((buf, e) => Buffer.concat([',
            '    buf, Buffer.from(`${e.mode} ${e.name}\\0`), Buffer.from(e.sha, "hex"),',
            '  ]), Buffer.alloc(0));',
            '  return writeObject("tree", body);   // hash + deflate + store',
            '}',
          ] },
        ],
      },
      {
        title: 'Commits are snapshots on a chain',
        body: 'A commit is not special; it is another object under the same rule. Its body names one tree (the snapshot), one parent commit, an author and a committer line carrying a Unix timestamp, a blank line, then the message. Wrap that in a `commit <size>\\0` header and it earns a SHA-1 like every blob and tree. The parent pointer is the whole trick behind history: each commit names the one before it, so a stack of immutable snapshots reads as a timeline.',
        blocks: [
          { kind: 'diagram', id: 'commit-chain', caption: 'HEAD to a branch ref to a chain of commits, each naming its parent.' },
          { kind: 'code', lang: 'js', caption: 'commit-tree.js', code: [
            'const body = Buffer.concat([',
            '  Buffer.from(`tree ${treeSha}\\n`),',
            '  Buffer.from(`parent ${parentSha}\\n`),',
            '  Buffer.from(`author ${name} <${email}> ${Date.now()} +0000\\n`),',
            '  Buffer.from(`committer ${name} <${email}> ${Date.now()} +0000\\n\\n`),',
            '  Buffer.from(`${message}\\n`),',
            ']);',
            'const sha = writeObject("commit", body);   // same envelope, same hashing',
          ] },
        ],
      },
      {
        title: 'Reading the objects back out',
        body: 'Reading is storing in reverse. Each command reads the object file, inflates it with `zlib`, and splits on the NUL that divides the header from the body. `cat-file -p` prints that body. `ls-tree --name-only` slices a tree\'s entries down to bare filenames. `log` resolves HEAD to its branch ref, inflates the commit there, pulls the parent hash out with a regular expression, and pages back through history one commit at a time, the way Git\'s own log does.',
        blocks: [
          { kind: 'code', lang: 'js', caption: 'cat-file.js + log-file.js (the read path)', code: [
            '// cat-file -p: inflate, then drop the "blob <size>\\0" header at the NUL',
            'const raw = zlib.inflateSync(fs.readFileSync(objectPath));',
            'process.stdout.write(raw.toString().split("\\0")[1]);',
            '',
            '// log: resolve HEAD to a commit, inflate it, follow the parent line back',
            'const commit = zlib.inflateSync(fs.readFileSync(objectPath)).toString();',
            'const parent = commit.match(/parent (?<sha>[0-9a-f]{40})/)?.groups.sha;',
          ] },
        ],
      },
      {
        title: 'One dispatcher, one class per verb, one honest cheat',
        body: '`main.js` reads `process.argv`, constructs the command object that matches the verb, and hands it to a `GitClient` whose entire job is to call `run()` on it. Every command is its own class behind that one method, and the program imports nothing from npm: `crypto` for SHA-1, `zlib` for framing, `fs` for the store, all built in. Two gaps are worth naming rather than hiding. `add` hashes a blob instead of keeping a real staging index, and `clone` is the single place the project shells out to the system `git` rather than speaking the pack protocol itself.',
        blocks: [
          { kind: 'diagram', id: 'dispatch', caption: 'argv selects a command class; a four-line client runs it.' },
          { kind: 'code', lang: 'js', caption: 'client.js + main.js (dispatch)', code: [
            'class GitClient {',
            '  run(command) { command.run(); }   // the entire dispatcher',
            '}',
            '',
            'switch (process.argv[2]) {',
            '  case "hash-object": client.run(new HashWrite(file));               break;',
            '  case "write-tree":  client.run(new WriteTree());                   break;',
            '  case "commit-tree": client.run(new CommitTree(tree, parent, msg)); break;',
            '  case "log":         client.run(new Log());                         break;',
            '  // ...one case, one class, per verb',
            '}',
          ] },
        ],
      },
    ],
    conclusion: [
      'Build Your Own Git is less about the tool than the idea beneath it: a store where a name is a hash of what it holds. Once `hash-object`, `write-tree`, and `commit-tree` agree on one envelope - type, size, NUL, body, deflated - blobs, trees, and commits stop being three features and become one operation pointed at different bytes.',
      'What sits here is the plumbing, scoped honestly: real objects the official `git` reads back, a Merkle shape that makes tampering show up, and a clear edge around the parts left as shortcuts. The porcelain above it - a staging index, branch management, the pack protocol a real clone speaks - is the next layer, and it would stand on exactly the object store this already builds.',
    ],
    figma: null,
    links: [
      { label: 'GitHub', href: 'https://github.com/23f3001304' },
    ],
  },
  {
    id: 'PRJ-006',
    slug: 'build-my-own-shell',
    name: 'Build My Own Shell',
    tagline: 'A POSIX shell in C++ - the read, parse, decide, exec loop behind every $ prompt, built from the syscalls up.',
    when: 'Oct → Nov 2024',
    status: 'ARCHIVED',
    stack: ['C++17', 'POSIX', 'fork / exec', 'CMake'],
    metrics: [
      { value: '6', unit: '', label: 'built-in commands' },
      { value: '3', unit: '', label: 'syscalls: fork · exec · wait' },
      { value: '0', unit: '', label: 'third-party dependencies' },
      { value: '2', unit: '', label: 'quote styles, parsed by hand' },
    ],
    sprite: '/oneko/oneko-dog.gif',
    accent: '#e0a106',
    overview: [
      'Build Your Own Shell is the program behind the $ prompt, written from the syscalls up in C++. It reads a line, decides whether the first word is one of its own built-ins or a program living somewhere on `$PATH`, and either handles it in-process or forks a child to run it. No readline, no libraries past the standard library and POSIX.',
      'The whole thing is a read-eval-print loop. `echo`, `pwd`, `cd`, `cat`, `type`, and `exit` are built in; everything else is resolved by walking `$PATH` and run through `fork` plus `execvp`, with the parent waiting on the child. A hand-written scanner handles the quoting and backslash escapes that make `echo \'a b\'` and `echo a\\ b` come out right.',
    ],
    sections: [
      {
        title: 'A shell is a loop',
        body: 'Print a prompt, read a line, work out what it means, run it, and come back for the next one. This shell is a literal `while (true)` in `main`: `std::getline` blocks for a line, `exit 0` is the one break condition, and `parse_command` splits the rest into words before anything is dispatched. Output is set unbuffered, so the prompt and a program\'s first bytes never get stuck behind a buffer.',
        blocks: [
          { kind: 'diagram', id: 'repl-loop', caption: 'Prompt, read, parse, dispatch, then loop until exit 0.' },
          { kind: 'code', lang: 'cpp', caption: 'main.cpp · the read-eval loop', code: [
            'while (true) {',
            '    std::cout << "$ ";                       // prompt (unbuffered)',
            '    std::string input;',
            '    std::getline(std::cin, input);           // block for a line',
            '    if (input == "exit 0") return 0;         // the one way out',
            '',
            '    std::vector<std::string> args = parse_command(input);',
            '    if (args.empty()) continue;',
            '    std::string command = args[0];',
            '',
            '    if (command == "echo")      execute_echo(input, args);',
            '    else if (command == "cd")   execute_cd(args);',
            '    else if (command == "type") execute_type(args, builtins);',
            '    // ... pwd, cat ...',
            '    else                        run_external(command, args);  // PATH + fork/exec',
            '}',
          ] },
        ],
      },
      {
        title: 'Built-in, or out on PATH?',
        body: 'The first word decides everything. If it is one of the six built-ins - `echo`, `pwd`, `cd`, `cat`, `type`, `exit` - the shell handles it inside its own process. Otherwise the word is a program name, resolved by walking `$PATH`: split the variable on colons and, for each directory, check whether `dir/command` exists, taking the first hit. The `type` built-in is that same logic turned inside out, reporting whether a name is built in or printing the exact path it would run.',
        blocks: [
          { kind: 'diagram', id: 'builtin-dispatch', caption: 'The first word: a built-in handled in process, or a program found on $PATH.' },
          { kind: 'code', lang: 'cpp', caption: 'shell_util.cpp · resolving a command on $PATH', code: [
            '// turn a bare name into a real path by walking $PATH, directory by directory',
            'std::string get_path(std::string command) {',
            '    std::stringstream ss(getenv("PATH"));',
            '    std::string dir;',
            '    while (std::getline(ss, dir, \':\')) {            // PATH is colon-separated',
            '        std::string candidate = dir + "/" + command;',
            '        if (std::filesystem::exists(candidate))',
            '            return candidate;                        // first match wins',
            '    }',
            '    return "";                                       // not on PATH',
            '}',
          ] },
        ],
      },
      {
        title: 'Running a program is three syscalls',
        body: 'Launching an external command is the classic Unix three-step. `fork` clones the process, and that one call returns twice: zero in the new child, the child\'s PID in the parent. The child calls `execvp`, which replaces its own image with the target program and never returns on success; the parent calls `waitpid` and blocks until the child finishes. `execvp` would search `$PATH` itself, but resolving the path first is what lets `type` work and gives a clean `command not found`.',
        blocks: [
          { kind: 'diagram', id: 'fork-exec', caption: 'One fork returns twice: the child execs the program, the parent waits.' },
          { kind: 'code', lang: 'cpp', caption: 'main.cpp · fork, exec, wait', code: [
            'pid_t pid = fork();',
            'if (pid == 0) {                          // child',
            '    execvp(path.c_str(), c_args.data()); // replace this process image',
            '    perror("execvp");                    // only reached if exec failed',
            '    exit(EXIT_FAILURE);',
            '} else if (pid > 0) {                    // parent',
            '    int status;',
            '    waitpid(pid, &status, 0);            // block until the child is done',
            '}',
          ] },
        ],
      },
      {
        title: 'Quoting and escapes, by hand',
        body: 'Most of a shell\'s surprises live in quoting. `echo \'a   b\'` should keep its spaces; `echo a\\ b` should fold the escaped space into a single argument. A character scanner walks the input, tracking whether it is inside a quote and which kind, stripping the quotes and emitting the literal text inside. What is deliberately not here is the rest of a real shell - pipes, redirection, globbing, job control, history. This is the spine: a loop, a builtin table, a `$PATH` walk, and `fork` plus `exec`.',
        blocks: [
          { kind: 'code', lang: 'cpp', caption: 'commands.cpp · quote and escape handling (condensed)', code: [
            '// strip quotes, honour backslash escapes - the fiddly part of any shell',
            'std::string filter(const std::string &in) {',
            '    std::string out;',
            '    char quote = 0;                       // 0, single, or double',
            '    for (size_t i = 0; i < in.size(); ++i) {',
            '        char c = in[i];',
            '        if (!quote && (c == \'\\\'\' || c == \'"\')) quote = c;   // open a quote',
            '        else if (c == quote)                   quote = 0;   // close it',
            '        else if (c == \'\\\\\' && !quote)          out += in[++i]; // escape next',
            '        else                                   out += c;',
            '    }',
            '    return out;',
            '}',
          ] },
        ],
      },
    ],
    conclusion: [
      'Build Your Own Shell makes the invisible visible. Every $ prompt runs this exact loop: read, parse, decide built-in or external, and for external, fork a child and exec the program inside it. Strip away pipes and history and what is left is surprisingly small, and surprisingly load-bearing.',
      'The honest scope is the point. No libraries past the standard one, no parser generator, no readline, just a loop, a handful of built-ins, a `$PATH` walk, and three syscalls. The features a real shell adds next - a pipe, a redirect, a glob - all bolt onto this same read-decide-run spine.',
    ],
    figma: null,
    links: [
      { label: 'GitHub', href: 'https://github.com/23f3001304' },
    ],
  },
];

export const projectBySlug = Object.fromEntries(projects.map((p) => [p.slug, p]));
