/* ============================================================
   World - the photo manifest.   GENERATED by scripts/gen-world.mjs.

   Drop <N>.webp files into /public/world and run:  npm run world
   src, dimensions (w/h) and alt are filled in automatically from the files.
   The ONLY field you set is `taken` (ISO 'YYYY-MM-DDTHH:mm'): it is auto-derived
   when the filename encodes a date, otherwise carried over from the previous
   manifest - so a date typed here survives the next regeneration.

   WORLD_V (in scripts/gen-world.mjs) appends ?v=N to every URL: bump it to bust
   the CDN/edge cache after replacing a photo, since /world/* isn't fingerprinted.

   PRIVACY: nothing is read from the image at runtime (no EXIF/GPS) - the date
   shown is only ever the `taken` value stored below.
   ============================================================ */
export const worldPhotos = [
  { src: '/world/1.webp?v=2', w: 1599, h: 1200, alt: 'Photograph 01', taken: null },
  { src: '/world/2.webp?v=2', w: 1152, h: 864,  alt: 'Photograph 02', taken: null },
  { src: '/world/3.webp?v=2', w: 1200, h: 1599, alt: 'Photograph 03', taken: null },
  { src: '/world/4.webp?v=2', w: 1599, h: 1599, alt: 'Photograph 04', taken: null },
  { src: '/world/5.webp?v=2', w: 1280, h: 720,  alt: 'Photograph 05', taken: null },
  { src: '/world/6.webp?v=2', w: 1599, h: 1200, alt: 'Photograph 06', taken: null },
  { src: '/world/7.webp?v=2', w: 864,  h: 1152, alt: 'Photograph 07', taken: null },
  { src: '/world/8.webp?v=2', w: 1200, h: 1599, alt: 'Photograph 08', taken: null },
  { src: '/world/9.webp?v=2', w: 620,  h: 1386, alt: 'Photograph 09', taken: null },
  { src: '/world/10.webp?v=2', w: 762,  h: 1280, alt: 'Photograph 10', taken: null },
  { src: '/world/11.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 11', taken: null },
  { src: '/world/12.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 12', taken: null },
  { src: '/world/13.webp?v=2', w: 1280, h: 960,  alt: 'Photograph 13', taken: null },
  { src: '/world/14.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 14', taken: null },
  { src: '/world/15.webp?v=2', w: 720,  h: 1280, alt: 'Photograph 15', taken: null },
  { src: '/world/16.webp?v=2', w: 1280, h: 720,  alt: 'Photograph 16', taken: null },
  { src: '/world/17.webp?v=2', w: 720,  h: 1280, alt: 'Photograph 17', taken: null },
  { src: '/world/18.webp?v=2', w: 720,  h: 1280, alt: 'Photograph 18', taken: null },
  { src: '/world/19.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 19', taken: null },
  { src: '/world/20.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 20', taken: null },
  { src: '/world/21.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 21', taken: null },
  { src: '/world/22.webp?v=2', w: 1280, h: 960,  alt: 'Photograph 22', taken: null },
  { src: '/world/23.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 23', taken: null },
  { src: '/world/24.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 24', taken: null },
  { src: '/world/25.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 25', taken: null },
  { src: '/world/26.webp?v=2', w: 1280, h: 960,  alt: 'Photograph 26', taken: '2025-07-16T19:28' },
  { src: '/world/27.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 27', taken: '2025-07-19T19:19' },
  { src: '/world/28.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 28', taken: '2025-07-24T18:29' },
  { src: '/world/29.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 29', taken: '2025-10-05T17:21' },
  { src: '/world/30.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 30', taken: '2025-10-05T17:25' },
  { src: '/world/31.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 31', taken: '2025-10-05T17:25' },
  { src: '/world/32.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 32', taken: '2025-10-05T17:34' },
  { src: '/world/33.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 33', taken: '2025-10-06T17:52' },
  { src: '/world/34.webp?v=2', w: 1280, h: 576,  alt: 'Photograph 34', taken: '2024-03-02T17:24' },
  { src: '/world/35.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 35', taken: '2025-01-08T18:28' },
  { src: '/world/36.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 36', taken: '2025-01-08T18:31' },
  { src: '/world/37.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 37', taken: null },
  { src: '/world/38.webp?v=2', w: 720,  h: 1280, alt: 'Photograph 38', taken: null },
  { src: '/world/39.webp?v=2', w: 720,  h: 1280, alt: 'Photograph 39', taken: null },
  { src: '/world/40.webp?v=2', w: 1280, h: 720,  alt: 'Photograph 40', taken: null },
  { src: '/world/41.webp?v=2', w: 1280, h: 720,  alt: 'Photograph 41', taken: null },
  { src: '/world/42.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 42', taken: null },
  { src: '/world/43.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 43', taken: null },
  { src: '/world/44.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 44', taken: null },
  { src: '/world/45.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 45', taken: null },
  { src: '/world/46.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 46', taken: null },
  { src: '/world/47.webp?v=2', w: 1280, h: 960,  alt: 'Photograph 47', taken: null },
  { src: '/world/48.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 48', taken: null },
  { src: '/world/49.webp?v=2', w: 1280, h: 960,  alt: 'Photograph 49', taken: null },
  { src: '/world/50.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 50', taken: null },
  { src: '/world/51.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 51', taken: null },
  { src: '/world/52.webp?v=2', w: 1280, h: 960,  alt: 'Photograph 52', taken: null },
  { src: '/world/53.webp?v=2', w: 1280, h: 960,  alt: 'Photograph 53', taken: null },
  { src: '/world/54.webp?v=2', w: 1280, h: 960,  alt: 'Photograph 54', taken: null },
  { src: '/world/55.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 55', taken: null },
  { src: '/world/56.webp?v=2', w: 1280, h: 960,  alt: 'Photograph 56', taken: null },
  { src: '/world/57.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 57', taken: null },
  { src: '/world/58.webp?v=2', w: 960,  h: 1280, alt: 'Photograph 58', taken: null },
];
